function vec = makeFeatureVec(window)
%MAKEFEATUREVEC(window) converts window into feature vector
% window - matrix like
% 	x0 y0 z0 ...
% 	x1 y1 z1 ...
% 	...
	vec = [	mean(A(:, 1)) ...
			mean(A(:, 2)) ...
			mean(A(:, 3)) ...

			mad(A(:, 1)) ...
			mad(A(:, 2)) ...
			mad(A(:, 3)) ...

			sum(A(:, 1)) ...
			sum(A(:, 2)) ...
			sum(A(:, 3))
	]
end
